parameter_defaults:
  DnsServers: ['10.11.5.19']

  ControlPlaneSubnet: leaf0
  ControllerControlPlaneSubnet: leaf0
  ComputeControlPlaneSubnet: leaf0
  ComputeOvsDpdkSriovControlPlaneSubnet: leaf0
  ComputeSriovControlPlaneSubnet: leaf0
  ComputeSriovOffloadControlPlaneSubnet: leaf0

  ControllerHostnameFormat: 'controller-%index%'
  ComputeSriovOffloadHostnameFormat: 'cmpt-offload-%index%'

  NeutronTunnelTypes: ''
  NeutronNetworkType: 'vlan'

  OvercloudControllerFlavor: "controller"
  #OvercloudComputeFlavor: "compute"
  #OvercloudComputeOvsDpdkFlavor: "compute"
  #OvercloudComputeOvsDpdkSriovFlavor: "compute"
  #OvercloudComputeSriovFlavor: "compute"
  OvercloudComputeSriovOffloadFlavor: "compute"

  ControllerCount: 1
  ComputeOvsDpdkSriovCount: 0
  ComputeSriovCount: 0
  ComputeSriovOffloadCount: 2

  NtpServer: "clock.redhat.com"
  #TimeZone: Kolkata
  SshServerOptions:
    UseDns: 'no'
    #TenantInterfaceRoutes:
    #  - test1: 1
    #    test2: 2
