resource_registry:
  OS::TripleO::ComputeOvsDpdkSriov::Net::SoftwareConfig: nic-configs/computeovsdpdksriov.yaml
  OS::TripleO::ComputeSriov::Net::SoftwareConfig: nic-configs/computesriov.yaml
  #OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ControllerSriov::Net::SoftwareConfig: nic-configs/controllersriov.yaml
  OS::TripleO::Servies::NeutronDhcpAgent: OS::Heat::None

parameter_defaults:
  NtpServer: "clock.redhat.com"
  SshServerOptions:
    UseDns: 'no'

  ControlPlaneDefaultRoute: "192.168.24.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['10.11.5.19']
  EC2MetadataIp: "192.168.24.1"

  NeutronExternalNetworkBridge: "'br-ex'"

  #ControllerCount: 1
  ControllerSriovCount: 1
  ComputeOvsDpdkSriovCount: 1
  ComputeSriovCount: 0
  OvercloudControllerSriovFlavor: controller
  #OvercloudControllerFlavor: controller
  OvercloudComputeOvsDpdkSriovFlavor: compute
  OvercloudComputeSriovFlavor: compute

  NeutronBridgeMappings: "datacentre:br-ex,data1:br-link0,sriov2:br-link1"
  NeutronFlatNetworks: "datacentre,data1,sriov2"
  NeutronNetworkVLANRanges: "data1:406:410,sriov2:406:410"
  NeutronNetworkType: ['geneve', 'vlan']
  NeutronTunnelTypes: "geneve"
  NeutronEnableDVR: false

  NovaPCIPassthrough:
    - devname: "eno4"
      trusted: "true"
      physical_network: "sriov2"
  NeutronPhysicalDevMappings: "sriov2:eno4"
  NeutronSriovAgentExtensions: qos
  NovaSchedulerDefaultFilters:
    - "RetryFilter"
    - "AvailabilityZoneFilter"
    - "ComputeFilter"
    - "ComputeCapabilitiesFilter"
    - "ImagePropertiesFilter"
    - "ServerGroupAntiAffinityFilter"
    - "ServerGroupAffinityFilter"
    - "PciPassthroughFilter"
    - "AggregateInstanceExtraSpecsFilter"
