resource_registry:
  OS::TripleO::ComputeOvsDpdkSriov::PreNetworkConfig: /usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml
  OS::TripleO::ComputeSriov::PreNetworkConfig: /usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml

parameter_defaults:
 ComputeOvsDpdkSriovParameters:
  OvsEnableDpdk: true
  OvsDpdkCoreList: 0-1,12-13
  OvsDpdkMemoryChannels: 4
  OvsPmdCoreList: 10-11,22-23
  NovaComputeCpuDedicatedSet: ['2-9','14-21']
  NovaComputeCpuSharedSet: ['0-1','12-13']
  IsolCpusList: 2-11,14-23
  KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt isolcpus=2-11,14-23
  #TunedProfileName: ""

 ComputeSriovParameters:
  IsolCpusList: 4-23
  KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt isolcpus=4-23
  NovaComputeCpuDedicatedSet: ['4-23']
  NovaComputeCpuSharedSet: ['0-3'] 
