resource_registry:
  OS::TripleO::ComputeSriovOffload::Net::SoftwareConfig: nic-configs/computesriov-offload.yaml
  OS::TripleO::ControllerSriov::Net::SoftwareConfig: nic-configs/controller-offload.yaml
  OS::TripleO::Servies::NeutronDhcpAgent: OS::Heat::None

  
parameter_defaults:
  NeutronBridgeMappings: 'datacentre:br-ex,tenant:br-offload'
  NeutronNetworkVLANRanges: 'tenant:502:505'
  NeutronFlatNetworks: 'datacentre,tenant'
  NeutronPhysicalDevMappings:
    - tenant:ens1f0
    - tenant:ens1f1

  NovaPCIPassthrough:
  - devname: "ens1f0"
    physical_network: "tenant"
  - devname: "ens1f1"
    physical_network: "tenant"

